# List of RSS feed URLs to fetch news from Portuguese news sources
RSS_FEEDS = [
    "https://www.record.pt/rss/",
    "https://www.autosport.pt/feed/",
    "https://www.zerozero.pt/rss/noticias.php",
    "https://visao.pt/feed/",
    "https://feeds.feedburner.com/publicoRSS",
    "https://jornaleconomico.sapo.pt/feed/",
    "https://www.cmjornal.pt/rss",
    "https://feeds.feedburner.com/expresso-geral",
    "https://www.jornaldenegocios.pt/rss",
    "https://www.rtp.pt/noticias/rss/",
    "https://rr.sapo.pt/rss/rssfeed.aspx?section=section_noticias",
    "https://rss.impresa.pt/feed/latest/expresso.rss?type=ARTICLE,VIDEO,STREAM,PLAYLIST,EVENT&limit=20&pubsubhub=true",
    "https://pt.euronews.com/rss?format=mrss&level=theme&name=news",
    "https://pplware.sapo.pt/feed/",
    "https://ionline.sapo.pt/feed/",
    "https://www.noticiasaominuto.com/rss/ultima-hora",
    "https://www.eurogamer.pt/feed",
    "https://pt.ign.com/feed.xml",
    "https://lusometeo.com/feed/",
    "https://tek.sapo.pt/rss",
    "https://www.sapo.pt/rss",
    "https://caras.pt/feed/"
]

# API sources that don't provide RSS feeds but have JSON endpoints
API_SOURCES = [
    {
        "url": "https://observador.pt/wp-json/obs_api/v4/news/widget",
        "headers": {"User-Agent": "Mozilla/5.0"},
        "source_name": "Observador"
    }
]

# Maps feed URLs to predefined categories
FEED_CATEGORY_MAPPER = {
    "https://pt.euronews.com/rss?format=mrss&level=theme&name=news": "Últimas",
    "https://feeds.feedburner.com/PublicoRSS" : "Últimas",
    
    "https://www.record.pt/rss": "Desporto",
    "https://www.autosport.pt/feed": "Desporto",
    "https://www.zerozero.pt/rss/noticias.php": "Desporto",
    "https://www.noticiasaominuto.com/rss/desporto": "Desporto",
    "https://rr.sapo.pt/rss/rssfeed.aspx?fid=2": "Desporto",
    "https://pt.euronews.com/sport": "Desporto",
    
    "https://jornaleconomico.sapo.pt/feed": "Economia",
    "https://www.jornaldenegocios.pt/rss": "Economia",
    "https://rr.sapo.pt/rss/rssfeed.aspx?fid=86": "Economia",
    "https://www.rtp.pt/noticias/rss/economia": "Economia",
    "https://www.noticiasaominuto.com/rss/economia": "Economia",

    "https://noticiasaominuto.com/rss/politica": "Política",
    "https://rr.sapo.pt/rss/rssfeed.aspx?fid=85": "Política",

    "https://rr.sapo.pt/rss/rssfeed.aspx?fid=6": "Nacional",
    "https://www.rtp.pt/noticias/rss/pais": "Nacional",
    "https://www.noticiasaominuto.com/rss/pais": "Nacional",

    "https://noticiasaominuto.com/rss/mundo": "Mundo",
    "https://www.rtp.pt/noticias/rss/mundo": "Mundo",
    "https://rr.sapo.pt/rss/rssfeed.aspx?fid=88": "Mundo",
    "https://rr.sapo.pt/rss/rssfeed.aspx?fid=84": "Mundo",
    "https://pt.euronews.com/my-europe": "Mundo",
    "https://pt.euronews.com/rss?format=mrss&level=program&name=nocomment": "Mundo",

    "https://www.noticiasaominuto.com/rss/cultura": "Cultura",
    "https://www.rtp.pt/noticias/rss/cultura": "Cultura",
    "https://pt.euronews.com/culture": "Cultura",

    "https://www.noticiasaominuto.com/rss/tech": "Ciência e Tech",
    "https://pt.euronews.com/rss?format=mrss&level=vertical&name=next": "Ciência e Tech",
    "https://pplware.sapo.pt/feed/": "Ciência e Tech",
    "https://www.eurogamer.pt/feed": "Ciência e Tech",
    "https://tek.sapo.pt/rss": "Ciência e Tech",

    "https://www.noticiasaominuto.com/rss/fama": "Sociedade",
    "https://www.noticiasaominuto.com/rss/lifestyle": "Sociedade",
    "https://rr.sapo.pt/rss/rssfeed.aspx?fid=89": "Sociedade",
    "https://lusometeo.com/feed/": "Sociedade",
    "https://pt.euronews.com/rss?format=mrss&level=vertical&name=green": "Sociedade",
    "https://pt.euronews.com/travel": "Sociedade",

    "https://www.rtp.pt/noticias/rss/videos": "Multimédia",
    "https://www.rtp.pt/noticias/rss/audios": "Multimédia",

    "https://caras.pt/feed/": "Lifestyle",

    "https://rr.sapo.pt/rss/rssfeed.aspx?fid=71": "Opinião",

    "https://www.eurogamer.pt/feed": "Vídeojogos",
    "https://pt.ign.com/feed.xml": "Vídeojogos"
}

# Maps specific category names to standardized category names
CATEGORY_MAPPER = {
    "Nacional": "Nacional",
    "País": "Nacional",
    "Pais": "Nacional",
    "Portugal": "Nacional",
    "Mundo": "Mundo",
    "Internacional": "Mundo",
    "União Europeia": "Mundo",
    "Guerra na Ucrânia": "Mundo",
    "Guerra no médio oriente": "Mundo",
    "Médio Oriente": "Mundo",
    "My-europe": "Mundo",
    "África": "Mundo",
    "Europa": "Mundo",
    "A guerra na Síria": "Mundo",
    "Guerra israel-hamas": "Mundo",
    "Faixa de Gaza": "Mundo",
    "Guerra no Médio Oriente": "Mundo",
    "Alemanha": "Mundo",
    "Diplomacia": "Mundo",
    "EUA": "Mundo",
    "Público Brasil": "Mundo",
    "Desporto": "Desporto",
    "Futebol": "Desporto",
    "Benfica": "Desporto",
    "Sporting": "Desporto",
    "Porto": "Desporto",
    "Modalidades": "Desporto",
    "Mais Modalidades": "Desporto",
    "Mais modalidades": "Desporto",
    "Futebol Nacional": "Desporto",
    "Futebol Internacional": "Desporto",
    "Futebol-internacional": "Desporto",
    "Liga D'Ouro": "Desporto",
    "Maismotores": "Desporto",
    "Liga Europa": "Desporto",
    "Velocidade": "Desporto",
    "Futebol nacional": "Desporto",
    "Motores": "Desporto",
    "Ralis": "Desporto",
    "Karting": "Desporto",
    "Formula1": "Desporto",
    "Auto": "Desporto",
    "Bola-branca": "Desporto",
    "Economia": "Economia",
    "Negócios": "Economia",
    "Segurança Social": "Economia",
    "Bolsa e Mercados": "Economia",
    "Mercados": "Economia",
    "Dinheiro": "Economia",
    "Energia": "Economia",
    "Empresas": "Economia",
    "Iniciativaseprodutos": "Economia",
    "Economia Expresso": "Economia",
    "Economia dia a dia": "Economia",
    "Finanças pessoais": "Economia",
    "Finanças públicas": "Economia",
    "Imobiliário": "Economia",
    "Cultura": "Cultura",
    "Livros": "Cultura",
    "Cinema": "Cultura",
    "Blitz": "Cultura",
    "Inimigo-publico": "Cultura",
    "Ciência e Tech": "Ciência e Tech",
    "Ciência & Tech": "Ciência e Tech",
    "Ciência": "Ciência e Tech",
    "Ciencia": "Ciência e Tech",
    "Tech": "Ciência e Tech",
    "Tecnologia": "Ciência e Tech",
    "Microsoft": "Ciência e Tech",
    "Inteligência Artificial": "Ciência e Tech",
    "Exame Informática Brand studio": "Ciência e Tech",
    "Gadgets": "Ciência e Tech",
    "Internet": "Ciência e Tech",
    "Direto do lab": "Ciência e Tech",
    "Exame Informática": "Ciência e Tech",
    "Exameinformatica": "Ciência e Tech",
    "Redes_sociais": "Ciência e Tech",
    "Exame": "Ciência e Tech",
    "Facebook": "Ciência e Tech",
    "Apple": "Ciência e Tech",
    "Smartphones-tablets": "Ciência e Tech",
    "Sociedade": "Sociedade",
    "Coronavírus": "Sociedade",
    "Mau tempo": "Sociedade",
    "Sustentabilidade": "Sociedade",
    "Animais": "Sociedade",
    "Ambiente": "Sociedade",
    "Insólitos": "Sociedade",
    "Meteorologia": "Sociedade",
    "Viver-com-saude": "Sociedade",
    "Revista": "Sociedade",
    "Transportes": "Sociedade",
    "Clube Expresso": "Sociedade",
    "Atualidade": "Sociedade",
    "Geração E": "Sociedade",
    "Alterações climáticas": "Sociedade",
    "Saúde": "Sociedade",
    "Clima": "Sociedade",
    "Religiao": "Sociedade",
    "Justiça": "Sociedade",
    "Expresso-fundamental": "Sociedade",
    "Previsao-de-longo-prazo": "Sociedade",
    "Previsao-diaria": "Sociedade",
    "Previsao-semanal": "Sociedade",
    "Analise-meteorologica": "Sociedade",
    "Visaosaude": "Sociedade",
    "Projetos Expresso": "Sociedade",
    "Oceanos": "Sociedade",
    "Política": "Política",
    "Politica": "Política",
    "Defesa": "Política",
    "Presidenciais 2026": "Política",
    "Parlamento": "Política",
    "Partidos": "Política",
    "Crise política": "Política",
    "Governo": "Política",
    "Legislativas 2025": "Política",
    "Multimédia": "Multimédia",
    "Multimedia": "Multimédia",
    "Video": "Multimédia",
    "Podcasts": "Multimédia",
    "Fotogaleria": "Multimédia",
    "No Princípio Era a Bola": "Multimédia",
    "O Mundo a Seus Pés": "Multimédia",
    "Contas Poupança": "Multimédia",
    "O CEO é o limite": "Multimédia",
    "Facto político": "Multimédia",
    "Alta definição": "Multimédia",
    "Expresso da Manhã": "Multimédia",
    "Isto É Gozar Com Quem Trabalha": "Multimédia",
    "Ana Gomes": "Multimédia",
    "Noticiários Desporto": "Multimédia",
    "Minuto Consumidor": "Multimédia",
    "Linhas Vermelhas": "Multimédia",
    "Noticiário Antena1": "Multimédia",
    "Leste Oeste de Nuno Rogeiro": "Multimédia",
    "Vídeos": "Multimédia",
    "O Divórcio do Sono": "Multimédia",
    "Tv Media": "Multimédia",
    "Tv-media": "Multimédia",
    "Cmtv": "Multimédia",
    "Opinião": "Opinião",
    "Opiniao": "Opinião",
    "Colunistas": "Opinião",
    "Nota editorial": "Opinião",
    "Editorial": "Opinião",
    "Linhas Direitas": "Opinião",
    "José jorge letria": "Opinião",
    "Liveblogs": "Opinião",
    "Artigos de Newsletter": "Opinão",
    "Lifestyle": "Lifestyle",
    "Comer e beber": "Lifestyle",
    "Gastronomia": "Lifestyle",
    "Vida": "Lifestyle",
    "Realeza": "Lifestyle",
    "Moda": "Lifestyle",
    "Truques-dicas": "Lifestyle",
    "Boa cama boa mesa": "Lifestyle",
    "Boa Cama Boa Mesa": "Lifestyle",
    "Boa-cama-boa-mesa": "Lifestyle",
    "Vidas": "Lifestyle",
    "Óscares": "Lifestyle",
    "Fama": "Lifestyle",
    "Visaose7e": "Lifestyle",
    "Viagens": "Lifestyle",
    "Famosos": "Lifestyle",
    "Decoracao": "Lifestyle",
    "Ideias": "Lifestyle",
    "Vídeojogos": "Vídeojogos",
    "Jogos": "Vídeojogos",
    "Record-gaming": "Vídeojogos",
    "Outras Notícias": "Outras Notícias"
}

# Date format patterns for parsing publication dates
DATE_FORMATS = [
    "%Y-%m-%d %H:%M:%S",
    "%a, %d %b %Y %H:%M:%S %z",
    "%a, %d %b %Y %H:%M:%S GMT%z",
    "%Y-%m-%dT%H:%M:%S%z",
    "%Y-%m-%dT%H:%M:%S.%f%z"
]
