[build]
  # A tua pasta public na branch data
  publish = "public"
  
  # Deploy da branch data onde estão os JSON
  base = ""

# Configuração otimizada para sistema simplificado
[[headers]]
  for = "/articles.json"
  [headers.values]
    Cache-Control = "public, max-age=900, must-revalidate"  # 15min
    Vary = "Accept-Encoding"
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/articles_search.json"
  [headers.values]
    Cache-Control = "public, max-age=1800, must-revalidate"  # 30min - muda menos
    Vary = "Accept-Encoding"
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/original_categories.json"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"  # 1h - raramente muda
    Vary = "Accept-Encoding"
    Content-Type = "application/json; charset=utf-8"
    
# Forçar compressão gzip no Netlify
[build.processing]
  skip_processing = false

# Headers de segurança gerais
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Ativar processamento automático do Netlify
[build.processing]
  skip_processing = false

# Compressão de assets
[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

# Otimizações específicas para o teu caso
[[redirects]]
  from = "/api/noticias"
  to = "/noticias.json"
  status = 200
  headers = {Content-Encoding = "gzip"}

# Configurações de compressão mais agressivas
[build.environment]
  NODE_VERSION = "18"