name: Atualizar JSON

on:
  schedule:
    - cron: "*/5 * * * *"  # Corre a cada 5 minutos
  workflow_dispatch:  # Permite execução manual

jobs:
  update_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: pip install requests fastapi

      - name: Executar script
        run: python RSS_API.py

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Fazer commit do JSON
        run: |
          git add articles.json
          git commit -m "Atualização automática do JSON"
          git push
        continue-on-error: true  # Evita falhas se não houver mudanças
