name: Atualizar JSON de Notícias e Enviar para FTP

on:
  schedule:
    - cron: "*/5 * * * *"  # Executa a cada 5 minutos
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script para atualizar JSON e enviar para FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: python RSS_API.py
